# Generated by Django 4.2 on 2024-10-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('BTH', 'BOOTH'), ('STB', 'STANDARD TABLE'), ('PTB', 'PARTY TABLE'), ('BTB', 'BANQUET TABLE'), ('STL', 'STOOL')], max_length=3)),
                ('seats', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
