# Generated by Django 5.1.2 on 2024-11-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistro', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='category',
            field=models.CharField(choices=[('BTH', 'BOOTH'), ('STB', 'STANDARD TABLE'), ('PTB', 'PARTY TABLE'), ('BTB', 'BANQUET TABLE')], max_length=3),
        ),
    ]
