# Generated by Django 5.1.5 on 2025-02-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bistro', '0004_workinghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True),
        ),
    ]
